#!/usr/bin/env python

import rospy

from fanuc_driver.hmi_driver import HmiDriver


def main():
    rospy.init_node('fanuc_hmi_node')
    rospy.loginfo('Starting %s', rospy.get_name())

    server = rospy.get_param('~robot_ip')
    assert isinstance(server, str)

    hmi_driver = HmiDriver(server)

    try:
        hmi_driver.system_startup()
        while not rospy.is_shutdown():
            hmi_driver.spin()
    except:
        if not rospy.is_shutdown():
            raise


if __name__ == '__main__':
    main()
