#!/usr/bin/env python

from fanuc_driver.action import ActionServer
import rospy


def main():
    rospy.init_node('fanuc_driver_driver')
    rospy.loginfo('Starting %s', rospy.get_name())

    server = rospy.get_param('~robot_ip')
    assert isinstance(server, str)

    traj_topic = '%s/follow_joint_trajectory' % rospy.get_name()
    try:
        action_server = ActionServer(
            traj_topic=traj_topic,
            server_address=server)
        rospy.spin()
    except:
        if not rospy.is_shutdown():
            raise

if __name__ == '__main__':
    main()
