#!/usr/bin/env python

from miso_fanuc.action import ActionServer
import rospy


def main():
    rospy.init_node('miso_fanuc_driver')
    rospy.loginfo('Starting %s', rospy.get_name())

    server = rospy.get_param('~robot_ip')
    assert isinstance(server, str)

    traj_topic = '%s/follow_joint_trajectory' % rospy.get_name()
    pneum_topic = rospy.get_param('~pneumatics_action_topic')
    try:
        action_server = ActionServer(
            traj_topic=traj_topic, pneum_topic=pneum_topic,
            server_address=server, sim=sim)
        rospy.spin()
    except:
        if not rospy.is_shutdown():
            raise

def 

if __name__ == '__main__':
    main()
