#!/usr/bin/env python

from control_msgs.msg import FollowJointTrajectoryAction, \
                             FollowJointTrajectoryGoal
import rospy


def generate_trajectory(length=10., period=2.):


def main():
    rospy.init_node('motion_demo')
    rospy.loginfo('Starting %s', rospy.get_name())
    try:
        rospy.sleep(10)
    except:
        if not rospy.is_shutdown():
            raise

if __name__ == '__main__':
    main()
